import { useEffect, useState } from 'react'
import { apiClient } from '@/api/client'
import type { AssemblyManifest } from './assemblyManifest'

export type { AssemblyManifest }

export interface AssemblyJoint {
  name: string
  type: 'revolute' | 'continuous' | 'prismatic' | 'fixed'
  parent_link: string
  child_link: string
  axis: [number, number, number]
  limits: { lower: number; upper: number } | null
}

/** Extended manifest with joints (generated by URDF parser) */
export interface AssemblyManifestWithJoints extends AssemblyManifest {
  joints?: AssemblyJoint[]
  display_names?: Record<string, string>
}

interface UseAssemblyManifestResult {
  manifest: AssemblyManifestWithJoints | null
  loading: boolean
  error: string | null
  hasManifest: boolean
}

const manifestCache = new Map<number, AssemblyManifestWithJoints | null>()

/** manifest 与它所属的 robotId 绑定存储，避免渲染期把上一台的数据交给新机型。 */
interface ManifestEntry {
  rid: number | undefined
  manifest: AssemblyManifestWithJoints | null
}

export function useAssemblyManifest(robotId: number | undefined): UseAssemblyManifestResult {
  const [entry, setEntry] = useState<ManifestEntry>({ rid: undefined, manifest: null })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!robotId) {
      setEntry({ rid: undefined, manifest: null })
      setLoading(false)
      return
    }

    // Check cache
    if (manifestCache.has(robotId)) {
      setEntry({ rid: robotId, manifest: manifestCache.get(robotId)! })
      setLoading(false)
      return
    }

    setLoading(true)
    setError(null)

    let cancelled = false

    const rid = robotId!

    async function fetchManifest() {
      try {
        const url = `/robots/${rid}/assets/manifests/assembly_manifest.json`
        const res = await apiClient.get<AssemblyManifestWithJoints>(url)
        if (!cancelled) {
          const data = res.data
          // Basic validation
          if (!data.rootNodeId || !data.nodes || !Array.isArray(data.nodes)) {
            throw new Error('Invalid manifest format')
          }
          manifestCache.set(rid, data)
          setEntry({ rid, manifest: data })
        }
      } catch (e: any) {
        if (!cancelled) {
          if (e.response?.status === 404) {
            // No manifest — not an error, just means no assembly view
            manifestCache.set(rid, null)
            setEntry({ rid, manifest: null })
          } else {
            setError(e.message || 'Failed to load manifest')
          }
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    fetchManifest()
    return () => { cancelled = true }
  }, [robotId])

  // 渲染期就按 robotId 校验：React 先渲染后跑 effect，若这里直接返回上一台的
  // manifest，子组件会用「新 robotId + 旧 link 名」发请求（实测切换机型时 29 个 404）。
  // 缓存命中时直接取用，避免已加载过的机型来回切换出现空白闪烁。
  const cached =
    robotId !== undefined && manifestCache.has(robotId)
      ? manifestCache.get(robotId)!
      : undefined
  const manifest =
    cached !== undefined ? cached : entry.rid === robotId ? entry.manifest : null

  return {
    manifest,
    loading,
    error,
    hasManifest: manifest !== null,
  }
}
