import { useEffect, useState } from 'react'
import { apiClient } from '@/api/client'
import type { AssemblyManifest } from './assemblyManifest'

export type { AssemblyManifest }

export interface AssemblyJoint {
  name: string
  type: 'revolute' | 'continuous' | 'prismatic' | 'fixed'
  parent_link: string
  child_link: string
  axis: [number, number, number]
  limits: { lower: number; upper: number } | null
}

/** Extended manifest with joints (generated by URDF parser) */
export interface AssemblyManifestWithJoints extends AssemblyManifest {
  joints?: AssemblyJoint[]
}

interface UseAssemblyManifestResult {
  manifest: AssemblyManifestWithJoints | null
  loading: boolean
  error: string | null
  hasManifest: boolean
}

const manifestCache = new Map<number, AssemblyManifestWithJoints | null>()

export function useAssemblyManifest(robotId: number | undefined): UseAssemblyManifestResult {
  const [manifest, setManifest] = useState<AssemblyManifestWithJoints | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!robotId) {
      setLoading(false)
      return
    }

    // Check cache
    if (manifestCache.has(robotId)) {
      setManifest(manifestCache.get(robotId)!)
      setLoading(false)
      return
    }

    let cancelled = false

    async function fetchManifest() {
      setLoading(true)
      setError(null)
      try {
        const url = `/api/v1/robots/${robotId}/assets/manifests/assembly_manifest.json`
        const res = await apiClient.get<AssemblyManifestWithJoints>(url)
        if (!cancelled) {
          const data = res.data
          // Basic validation
          if (!data.rootNodeId || !data.nodes || !Array.isArray(data.nodes)) {
            throw new Error('Invalid manifest format')
          }
          manifestCache.set(robotId, data)
          setManifest(data)
        }
      } catch (e: any) {
        if (!cancelled) {
          if (e.response?.status === 404) {
            // No manifest — not an error, just means no assembly view
            manifestCache.set(robotId, null)
            setManifest(null)
          } else {
            setError(e.message || 'Failed to load manifest')
          }
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    fetchManifest()
    return () => { cancelled = true }
  }, [robotId])

  return {
    manifest,
    loading,
    error,
    hasManifest: manifest !== null,
  }
}
