"""add sop version and target_module

Revision ID: 092b0539cc93
Revises: 20260515_timestamptz
Create Date: 2026-05-18 23:38:50.111901+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '092b0539cc93'
down_revision: Union[str, None] = '20260515_timestamptz'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # embedding_vec 列/索引由 20260308_v03_pgvector_chunks 条件创建（无 pgvector 扩展时整体跳过），
    # 因此这里必须用 IF EXISTS 保持对称，否则无 pgvector 环境（如官方 postgres:16 镜像）全新建库失败。
    op.execute('DROP INDEX IF EXISTS ix_ai_knowledge_chunks_embedding_vec')
    op.create_index(op.f('ix_ai_knowledge_chunks_attempt_id'), 'ai_knowledge_chunks', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_chunks_course_id'), 'ai_knowledge_chunks', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_chunks_owner_user_id'), 'ai_knowledge_chunks', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_chunks_source_id'), 'ai_knowledge_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_chunks_source_type'), 'ai_knowledge_chunks', ['source_type'], unique=False)
    op.execute('ALTER TABLE ai_knowledge_chunks DROP COLUMN IF EXISTS embedding_vec')
    op.create_index(op.f('ix_alignment_map_anchor_key'), 'alignment_map', ['anchor_key'], unique=False)
    op.create_index(op.f('ix_alignment_map_created_at'), 'alignment_map', ['created_at'], unique=False)
    op.create_index(op.f('ix_alignment_map_id'), 'alignment_map', ['id'], unique=False)
    op.create_index(op.f('ix_alignment_map_ref_id'), 'alignment_map', ['ref_id'], unique=False)
    op.create_index(op.f('ix_alignment_map_segment_id'), 'alignment_map', ['segment_id'], unique=False)
    op.create_index(op.f('ix_alignment_map_timeline_id'), 'alignment_map', ['timeline_id'], unique=False)
    op.alter_column('analysis_tasks', 'task_type',
               existing_type=postgresql.ENUM('pdf_extract', 'cad_parse', 'sop_generate', 'full', name='analysistasktype'),
               comment='任务类型',
               existing_nullable=False)
    op.alter_column('analysis_tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'failed', name='analysistaskstatus'),
               comment='任务状态',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::analysistaskstatus"))
    op.alter_column('analysis_tasks', 'input_document_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='输入文档 ID 列表',
               existing_nullable=True)
    op.alter_column('analysis_tasks', 'output_summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='分析结果摘要',
               existing_nullable=True)
    op.alter_column('analysis_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment='失败原因',
               existing_nullable=True)
    op.alter_column('analysis_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成时间',
               existing_nullable=True)
    op.create_index(op.f('ix_analysis_tasks_id'), 'analysis_tasks', ['id'], unique=False)
    op.alter_column('audit_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('belief_state_records', sa.Column('belief_metadata', sa.JSON(), nullable=True))
    op.drop_column('belief_state_records', 'metadata')
    op.drop_index(op.f('ix_commands_idempotency_key'), table_name='commands')
    op.create_index(op.f('ix_commands_idempotency_key'), 'commands', ['idempotency_key'], unique=True)
    op.alter_column('conversation_turns', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('conversation_turns', 'task_id',
               existing_type=sa.VARCHAR(length=64),
               comment='任务ID',
               existing_nullable=True)
    op.alter_column('conversation_turns', 'step_index',
               existing_type=sa.INTEGER(),
               comment='步骤索引',
               existing_nullable=True)
    op.alter_column('conversation_turns', 'role',
               existing_type=sa.VARCHAR(length=16),
               comment='角色: user/assistant/system',
               existing_nullable=False)
    op.alter_column('conversation_turns', 'content',
               existing_type=sa.TEXT(),
               comment='对话内容',
               existing_nullable=False)
    op.alter_column('conversation_turns', 'metadata',
               existing_type=sa.VARCHAR(length=512),
               comment='元数据 JSON',
               existing_nullable=True)
    op.alter_column('conversation_turns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_conversation_turns_created_at'), 'conversation_turns', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_turns_id'), 'conversation_turns', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_session_id'), 'conversation_turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_task_id'), 'conversation_turns', ['task_id'], unique=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='事件类型',
               existing_nullable=False)
    op.alter_column('events', 'step_index',
               existing_type=sa.INTEGER(),
               comment='步骤索引',
               existing_nullable=True)
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='事件时间',
               existing_nullable=False)
    op.alter_column('events', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='执行的操作',
               existing_nullable=True)
    op.alter_column('events', 'target',
               existing_type=sa.VARCHAR(length=100),
               comment='操作目标',
               existing_nullable=True)
    op.alter_column('events', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='操作参数',
               existing_nullable=True)
    op.alter_column('events', 'result',
               existing_type=sa.VARCHAR(length=50),
               comment='执行结果',
               existing_nullable=True)
    op.alter_column('events', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment='执行耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('events', 'is_error',
               existing_type=sa.BOOLEAN(),
               comment='是否为错误',
               existing_nullable=False)
    op.alter_column('events', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误消息',
               existing_nullable=True)
    op.create_index(op.f('ix_evidence_cards_attempt_id'), 'evidence_cards', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_evidence_cards_created_at'), 'evidence_cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_cards_id'), 'evidence_cards', ['id'], unique=False)
    op.alter_column('fault_cases', 'fault_code',
               existing_type=sa.VARCHAR(length=50),
               comment='故障代码',
               existing_nullable=False)
    op.alter_column('fault_cases', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='故障名称',
               existing_nullable=False)
    op.alter_column('fault_cases', 'description',
               existing_type=sa.TEXT(),
               comment='故障描述',
               existing_nullable=False)
    op.alter_column('fault_cases', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='故障分类',
               existing_nullable=True)
    op.alter_column('fault_cases', 'severity',
               existing_type=sa.VARCHAR(length=20),
               comment='严重程度',
               existing_nullable=True)
    op.alter_column('fault_cases', 'affected_parts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='受影响部件列表',
               existing_nullable=True)
    op.alter_column('fault_cases', 'symptoms',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='故障症状',
               existing_nullable=True)
    op.alter_column('fault_cases', 'diagnosis_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='诊断步骤',
               existing_nullable=True)
    op.alter_column('fault_cases', 'solution_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='解决步骤',
               existing_nullable=True)
    op.alter_column('fault_sop_mappings', 'fault_type',
               existing_type=sa.VARCHAR(length=50),
               comment='故障类型编码',
               existing_nullable=False)
    op.alter_column('fault_sop_mappings', 'sop_id',
               existing_type=sa.INTEGER(),
               comment='关联 SOP ID',
               existing_nullable=False)
    op.alter_column('fault_sop_mappings', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               comment='难度: beginner/intermediate/advanced',
               existing_nullable=False,
               existing_server_default=sa.text("'beginner'::character varying"))
    op.alter_column('fault_sop_mappings', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='优先级（同 fault_type 多 SOP 时）',
               existing_server_default=sa.text('1'))
    op.alter_column('fault_sop_mappings', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment='关联机器人型号 ID',
               existing_nullable=True)
    op.create_index(op.f('ix_fault_sop_mappings_id'), 'fault_sop_mappings', ['id'], unique=False)
    op.drop_constraint(op.f('fault_sop_mappings_sop_id_fkey'), 'fault_sop_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'fault_sop_mappings', 'sops', ['sop_id'], ['id'], ondelete='CASCADE')
    op.alter_column('knowledge_documents', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               comment='文档标题',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'content',
               existing_type=sa.TEXT(),
               comment='文档全文',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               comment='manual/guide/spec',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('knowledge_documents', 'fault_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               comment='关联故障标签 ["E001_OVERHEAT"]',
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('knowledge_documents', 'sop_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               comment='关联SOP标签',
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('knowledge_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='PENDING/APPROVED/EXPIRED',
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('knowledge_documents', 'risk_level',
               existing_type=sa.VARCHAR(length=5),
               comment='风险等级',
               existing_nullable=True,
               existing_server_default=sa.text("'R0'::character varying"))
    op.alter_column('knowledge_documents', 'uploaded_by',
               existing_type=sa.INTEGER(),
               comment='上传用户 ID',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment='关联机器人型号 ID',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'generation_status',
               existing_type=sa.VARCHAR(length=20),
               comment='生成状态: manual/ai_draft/published',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.drop_column('knowledge_documents', 'source')
    op.create_index(op.f('ix_multimodal_timelines_created_at'), 'multimodal_timelines', ['created_at'], unique=False)
    op.create_index(op.f('ix_multimodal_timelines_created_by_user_id'), 'multimodal_timelines', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_multimodal_timelines_id'), 'multimodal_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_multimodal_timelines_scope_id'), 'multimodal_timelines', ['scope_id'], unique=False)
    op.create_index(op.f('ix_multimodal_timelines_scope_type'), 'multimodal_timelines', ['scope_type'], unique=False)
    op.create_index(op.f('ix_multimodal_timelines_trace_id'), 'multimodal_timelines', ['trace_id'], unique=False)
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.alter_column('robot_assets', 'asset_type',
               existing_type=postgresql.ENUM('model_glb', 'manifest', 'thumbnail', 'upload_original', name='assettype'),
               comment='资产类型',
               existing_nullable=False)
    op.alter_column('robot_assets', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='相对存储路径',
               existing_nullable=False)
    op.alter_column('robot_assets', 'file_size',
               existing_type=sa.INTEGER(),
               comment='文件大小（字节）',
               existing_nullable=True)
    op.alter_column('robot_assets', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='元数据（顶点数、节点数等）',
               existing_nullable=True)
    op.create_index(op.f('ix_robot_assets_id'), 'robot_assets', ['id'], unique=False)
    op.alter_column('robot_models', 'brand',
               existing_type=sa.VARCHAR(length=100),
               comment='品牌',
               existing_nullable=False)
    op.alter_column('robot_models', 'model_name',
               existing_type=sa.VARCHAR(length=200),
               comment='型号名称',
               existing_nullable=False)
    op.alter_column('robot_models', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='版本号',
               existing_nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('robot_models', 'owner_teacher_id',
               existing_type=sa.INTEGER(),
               comment='创建者教师 ID（null 表示系统内置）',
               existing_nullable=True)
    op.alter_column('robot_models', 'visibility',
               existing_type=postgresql.ENUM('private', 'shared', name='robotvisibility'),
               comment='可见性: private/shared',
               existing_nullable=False,
               existing_server_default=sa.text("'private'::robotvisibility"))
    op.alter_column('robot_models', 'status',
               existing_type=postgresql.ENUM('draft', 'analyzing', 'ready', name='robotstatus'),
               comment='状态: draft/analyzing/ready',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::robotstatus"))
    op.alter_column('robot_models', 'description',
               existing_type=sa.TEXT(),
               comment='机器人描述',
               existing_nullable=True)
    op.alter_column('robot_models', 'thumbnail_path',
               existing_type=sa.VARCHAR(length=500),
               comment='缩略图相对路径',
               existing_nullable=True)
    op.create_index(op.f('ix_robot_models_id'), 'robot_models', ['id'], unique=False)
    op.drop_constraint(op.f('ux_roles_name'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(op.f('schools_name_key'), 'schools', type_='unique')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=True)
    op.create_index(op.f('ix_session_step_records_id'), 'session_step_records', ['id'], unique=False)
    op.drop_constraint(op.f('session_step_records_session_id_fkey'), 'session_step_records', type_='foreignkey')
    op.create_foreign_key(None, 'session_step_records', 'training_sessions', ['session_id'], ['session_id'])
    op.alter_column('snapshots', 'step_index',
               existing_type=sa.INTEGER(),
               comment='步骤索引',
               existing_nullable=False)
    op.alter_column('snapshots', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='快照时间',
               existing_nullable=False)
    op.alter_column('snapshots', 'trigger',
               existing_type=sa.VARCHAR(length=50),
               comment='触发原因：step_execution/manual/error',
               existing_nullable=False)
    op.alter_column('snapshots', 'joint_states',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关节状态列表',
               existing_nullable=False)
    op.alter_column('snapshots', 'sensor_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='传感器数据',
               existing_nullable=False)
    op.alter_column('snapshots', 'active_faults',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='活动故障列表',
               existing_nullable=True)
    op.alter_column('snapshots', 'adapter_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Adapter类型',
               existing_nullable=True)
    op.alter_column('sop_audit_logs', 'event_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='事件发生时间',
               existing_nullable=False)
    op.alter_column('sop_audit_logs', 'ingest_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='记录入库时间',
               existing_nullable=False)
    op.alter_column('sop_steps', 'step_index',
               existing_type=sa.INTEGER(),
               comment='步骤索引（从1开始）',
               existing_nullable=False)
    op.alter_column('sop_steps', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='步骤标题',
               existing_nullable=False)
    op.alter_column('sop_steps', 'description',
               existing_type=sa.TEXT(),
               comment='步骤描述',
               existing_nullable=False)
    op.alter_column('sop_steps', 'target_part',
               existing_type=sa.VARCHAR(length=100),
               comment='目标部件ID',
               existing_nullable=True)
    op.alter_column('sop_steps', 'expected_action',
               existing_type=sa.VARCHAR(length=50),
               comment='期望操作',
               existing_nullable=False)
    op.alter_column('sop_steps', 'action_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='操作参数（JSON）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'validation_rules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='验证规则（JSON）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'is_critical',
               existing_type=sa.BOOLEAN(),
               comment='是否为关键步骤',
               existing_nullable=True)
    op.alter_column('sop_steps', 'severity_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='严重程度等级：INFO/WARN/SAFETY_HALT',
               existing_server_default=sa.text("'WARN'::character varying"))
    op.alter_column('sop_steps', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               comment='超时时长（秒）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'allow_skip',
               existing_type=sa.BOOLEAN(),
               comment='是否允许跳过',
               existing_nullable=True)
    op.alter_column('sop_steps', 'hints',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='提示信息（JSON）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'tools_required',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='所需工具列表（JSON）',
               existing_nullable=True)
    op.add_column('sops', sa.Column('version', sa.String(length=20), nullable=True, comment='SOP版本号'))
    op.add_column('sops', sa.Column('target_module', sa.String(length=100), nullable=True, comment='目标维护模块'))
    op.alter_column('sops', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='SOP名称',
               existing_nullable=False)
    op.alter_column('sops', 'description',
               existing_type=sa.TEXT(),
               comment='SOP描述',
               existing_nullable=True)
    op.alter_column('sops', 'applicable_model',
               existing_type=sa.VARCHAR(length=100),
               comment='适用机器人型号',
               existing_nullable=False)
    op.alter_column('sops', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='分类',
               existing_nullable=True)
    op.alter_column('sops', 'difficulty_level',
               existing_type=sa.VARCHAR(length=20),
               comment='难度等级：low/medium/high',
               existing_nullable=True)
    op.alter_column('sops', 'estimated_time',
               existing_type=sa.INTEGER(),
               comment='预估时长（秒）',
               existing_nullable=True)
    op.alter_column('sops', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment='关联机器人型号 ID',
               existing_nullable=True)
    op.drop_constraint(op.f('student_skill_profiles_user_id_key'), 'student_skill_profiles', type_='unique')
    op.create_index(op.f('ix_student_skill_profiles_id'), 'student_skill_profiles', ['id'], unique=False)
    op.drop_constraint(op.f('student_skill_profiles_user_id_fkey'), 'student_skill_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_skill_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_student_weak_steps_step_id'), table_name='student_weak_steps')
    op.drop_index(op.f('ix_student_weak_steps_user_step'), table_name='student_weak_steps')
    op.create_index(op.f('ix_student_weak_steps_id'), 'student_weak_steps', ['id'], unique=False)
    op.drop_constraint(op.f('student_weak_steps_user_id_fkey'), 'student_weak_steps', type_='foreignkey')
    op.create_foreign_key(None, 'student_weak_steps', 'users', ['user_id'], ['id'])
    op.alter_column('task_executions', 'student_id',
               existing_type=sa.INTEGER(),
               comment='学生 user ID',
               existing_nullable=False)
    op.alter_column('task_executions', 'diagnosis_trace_id',
               existing_type=sa.VARCHAR(length=100),
               comment='诊断追踪 ID',
               existing_nullable=True)
    op.alter_column('task_executions', 'fault_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='故障类型')
    op.alter_column('task_executions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='in_progress/completed/abandoned',
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress'::character varying"))
    op.alter_column('task_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_task_executions_id'), 'task_executions', ['id'], unique=False)
    op.drop_constraint(op.f('task_executions_task_id_fkey'), 'task_executions', type_='foreignkey')
    op.drop_constraint(op.f('task_executions_student_id_fkey'), 'task_executions', type_='foreignkey')
    op.drop_constraint(op.f('task_executions_sop_id_fkey'), 'task_executions', type_='foreignkey')
    op.create_foreign_key(None, 'task_executions', 'sops', ['sop_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task_executions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_executions', 'report_url')
    op.drop_column('task_executions', 'total_duration_seconds')
    op.alter_column('task_step_results', 'step_index',
               existing_type=sa.INTEGER(),
               comment='步骤序号',
               existing_nullable=False)
    op.alter_column('task_step_results', 'status',
               existing_type=sa.VARCHAR(),
               comment='completed/skipped/failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('task_step_results', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               comment='耗时秒数',
               existing_nullable=True)
    op.alter_column('task_step_results', 'evidence_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               comment='photo/numeric/checkbox',
               existing_nullable=True)
    op.alter_column('task_step_results', 'evidence_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='证据内容',
               existing_nullable=True)
    op.alter_column('task_step_results', 'is_compliant',
               existing_type=sa.BOOLEAN(),
               comment='是否合规',
               existing_nullable=True)
    op.alter_column('task_step_results', 'feedback',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='即时反馈',
               existing_nullable=True)
    op.create_index(op.f('ix_task_step_results_id'), 'task_step_results', ['id'], unique=False)
    op.drop_constraint(op.f('task_step_results_execution_id_fkey'), 'task_step_results', type_='foreignkey')
    op.create_foreign_key(None, 'task_step_results', 'task_executions', ['execution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_step_results', 'completed_at')
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='任务标题',
               existing_nullable=False)
    op.alter_column('tasks', 'sop_id',
               existing_type=sa.INTEGER(),
               comment='关联SOP ID（可为NULL）',
               existing_nullable=True)
    op.alter_column('tasks', 'assignment_id',
               existing_type=sa.INTEGER(),
               comment='关联教学作业 ID（可为NULL）',
               existing_nullable=True)
    op.alter_column('tasks', 'guidance_policy_id',
               existing_type=sa.INTEGER(),
               comment='关联引导策略 ID（可为NULL）',
               existing_nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               comment='执行用户ID',
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态',
               existing_nullable=False)
    op.alter_column('tasks', 'current_step_index',
               existing_type=sa.INTEGER(),
               comment='当前步骤索引',
               existing_nullable=False)
    op.alter_column('tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始时间',
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('tasks', 'paused_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='暂停时间',
               existing_nullable=True)
    op.alter_column('tasks', 'time_limit',
               existing_type=sa.INTEGER(),
               comment='时间限制（秒）',
               existing_nullable=True)
    op.alter_column('tasks', 'pass_score',
               existing_type=sa.INTEGER(),
               comment='及格分数',
               existing_nullable=False)
    op.alter_column('tasks', 'final_score',
               existing_type=sa.INTEGER(),
               comment='最终得分',
               existing_nullable=True)
    op.alter_column('tasks', 'is_passed',
               existing_type=sa.BOOLEAN(),
               comment='是否通过',
               existing_nullable=True)
    op.alter_column('teacher_robot_bindings', 'teacher_id',
               existing_type=sa.INTEGER(),
               comment='教师用户 ID',
               existing_nullable=False)
    op.alter_column('teacher_robot_bindings', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment='机器人型号 ID',
               existing_nullable=False)
    op.alter_column('teacher_robot_bindings', 'binding_type',
               existing_type=sa.VARCHAR(length=20),
               comment='绑定类型: owner/shared_ref',
               existing_nullable=False,
               existing_server_default=sa.text("'owner'::character varying"))
    op.create_index(op.f('ix_teacher_robot_bindings_id'), 'teacher_robot_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_segments_created_at'), 'timeline_segments', ['created_at'], unique=False)
    op.create_index(op.f('ix_timeline_segments_end_ts_ms'), 'timeline_segments', ['end_ts_ms'], unique=False)
    op.create_index(op.f('ix_timeline_segments_id'), 'timeline_segments', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_segments_ref_id'), 'timeline_segments', ['ref_id'], unique=False)
    op.create_index(op.f('ix_timeline_segments_segment_type'), 'timeline_segments', ['segment_type'], unique=False)
    op.create_index(op.f('ix_timeline_segments_start_ts_ms'), 'timeline_segments', ['start_ts_ms'], unique=False)
    op.create_index(op.f('ix_timeline_segments_timeline_id'), 'timeline_segments', ['timeline_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_id'), 'training_sessions', ['id'], unique=False)
    op.create_foreign_key(None, 'training_sessions', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_training_submissions_id'), 'training_submissions', ['id'], unique=False)
    op.drop_constraint(op.f('training_submissions_submitted_by_fkey'), 'training_submissions', type_='foreignkey')
    op.drop_constraint(op.f('training_submissions_session_id_fkey'), 'training_submissions', type_='foreignkey')
    op.drop_constraint(op.f('training_submissions_user_id_fkey'), 'training_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'training_submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'training_submissions', 'training_sessions', ['session_id'], ['session_id'])
    op.create_foreign_key(None, 'training_submissions', 'users', ['submitted_by'], ['id'])
    op.drop_constraint(op.f('user_preferences_user_id_key'), 'user_preferences', type_='unique')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.drop_constraint(op.f('user_preferences_user_id_fkey'), 'user_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'user_preferences', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('ux_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('ux_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('user_preferences_user_id_fkey'), 'user_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_preferences_user_id_key'), 'user_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'training_submissions', type_='foreignkey')
    op.drop_constraint(None, 'training_submissions', type_='foreignkey')
    op.drop_constraint(None, 'training_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('training_submissions_user_id_fkey'), 'training_submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('training_submissions_session_id_fkey'), 'training_submissions', 'training_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('training_submissions_submitted_by_fkey'), 'training_submissions', 'users', ['submitted_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_training_submissions_id'), table_name='training_submissions')
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_training_sessions_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_timeline_segments_timeline_id'), table_name='timeline_segments')
    op.drop_index(op.f('ix_timeline_segments_start_ts_ms'), table_name='timeline_segments')
    op.drop_index(op.f('ix_timeline_segments_segment_type'), table_name='timeline_segments')
    op.drop_index(op.f('ix_timeline_segments_ref_id'), table_name='timeline_segments')
    op.drop_index(op.f('ix_timeline_segments_id'), table_name='timeline_segments')
    op.drop_index(op.f('ix_timeline_segments_end_ts_ms'), table_name='timeline_segments')
    op.drop_index(op.f('ix_timeline_segments_created_at'), table_name='timeline_segments')
    op.drop_index(op.f('ix_teacher_robot_bindings_id'), table_name='teacher_robot_bindings')
    op.alter_column('teacher_robot_bindings', 'binding_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='绑定类型: owner/shared_ref',
               existing_nullable=False,
               existing_server_default=sa.text("'owner'::character varying"))
    op.alter_column('teacher_robot_bindings', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='机器人型号 ID',
               existing_nullable=False)
    op.alter_column('teacher_robot_bindings', 'teacher_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='教师用户 ID',
               existing_nullable=False)
    op.alter_column('tasks', 'is_passed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否通过',
               existing_nullable=True)
    op.alter_column('tasks', 'final_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='最终得分',
               existing_nullable=True)
    op.alter_column('tasks', 'pass_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='及格分数',
               existing_nullable=False)
    op.alter_column('tasks', 'time_limit',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='时间限制（秒）',
               existing_nullable=True)
    op.alter_column('tasks', 'paused_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='暂停时间',
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('tasks', 'current_step_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='当前步骤索引',
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务状态',
               existing_nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='执行用户ID',
               existing_nullable=True)
    op.alter_column('tasks', 'guidance_policy_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联引导策略 ID（可为NULL）',
               existing_nullable=True)
    op.alter_column('tasks', 'assignment_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联教学作业 ID（可为NULL）',
               existing_nullable=True)
    op.alter_column('tasks', 'sop_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联SOP ID（可为NULL）',
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='任务标题',
               existing_nullable=False)
    op.add_column('task_step_results', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_step_results', type_='foreignkey')
    op.create_foreign_key(op.f('task_step_results_execution_id_fkey'), 'task_step_results', 'task_executions', ['execution_id'], ['id'])
    op.drop_index(op.f('ix_task_step_results_id'), table_name='task_step_results')
    op.alter_column('task_step_results', 'feedback',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='即时反馈',
               existing_nullable=True)
    op.alter_column('task_step_results', 'is_compliant',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否合规',
               existing_nullable=True)
    op.alter_column('task_step_results', 'evidence_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='证据内容',
               existing_nullable=True)
    op.alter_column('task_step_results', 'evidence_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='photo/numeric/checkbox',
               existing_nullable=True)
    op.alter_column('task_step_results', 'duration_seconds',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='耗时秒数',
               existing_nullable=True)
    op.alter_column('task_step_results', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='completed/skipped/failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('task_step_results', 'step_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='步骤序号',
               existing_nullable=False)
    op.add_column('task_executions', sa.Column('total_duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('task_executions', sa.Column('report_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_executions', type_='foreignkey')
    op.drop_constraint(None, 'task_executions', type_='foreignkey')
    op.create_foreign_key(op.f('task_executions_sop_id_fkey'), 'task_executions', 'sops', ['sop_id'], ['id'])
    op.create_foreign_key(op.f('task_executions_student_id_fkey'), 'task_executions', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('task_executions_task_id_fkey'), 'task_executions', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_task_executions_id'), table_name='task_executions')
    op.alter_column('task_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_executions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='in_progress/completed/abandoned',
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress'::character varying"))
    op.alter_column('task_executions', 'fault_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='故障类型')
    op.alter_column('task_executions', 'diagnosis_trace_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='诊断追踪 ID',
               existing_nullable=True)
    op.alter_column('task_executions', 'student_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='学生 user ID',
               existing_nullable=False)
    op.drop_constraint(None, 'student_weak_steps', type_='foreignkey')
    op.create_foreign_key(op.f('student_weak_steps_user_id_fkey'), 'student_weak_steps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_student_weak_steps_id'), table_name='student_weak_steps')
    op.create_index(op.f('ix_student_weak_steps_user_step'), 'student_weak_steps', ['user_id', 'step_id'], unique=True)
    op.create_index(op.f('ix_student_weak_steps_step_id'), 'student_weak_steps', ['step_id'], unique=False)
    op.drop_constraint(None, 'student_skill_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('student_skill_profiles_user_id_fkey'), 'student_skill_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_student_skill_profiles_id'), table_name='student_skill_profiles')
    op.create_unique_constraint(op.f('student_skill_profiles_user_id_key'), 'student_skill_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('sops', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联机器人型号 ID',
               existing_nullable=True)
    op.alter_column('sops', 'estimated_time',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='预估时长（秒）',
               existing_nullable=True)
    op.alter_column('sops', 'difficulty_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='难度等级：low/medium/high',
               existing_nullable=True)
    op.alter_column('sops', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='分类',
               existing_nullable=True)
    op.alter_column('sops', 'applicable_model',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='适用机器人型号',
               existing_nullable=False)
    op.alter_column('sops', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='SOP描述',
               existing_nullable=True)
    op.alter_column('sops', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='SOP名称',
               existing_nullable=False)
    op.drop_column('sops', 'target_module')
    op.drop_column('sops', 'version')
    op.alter_column('sop_steps', 'tools_required',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='所需工具列表（JSON）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'hints',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='提示信息（JSON）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'allow_skip',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否允许跳过',
               existing_nullable=True)
    op.alter_column('sop_steps', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='超时时长（秒）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'severity_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='严重程度等级：INFO/WARN/SAFETY_HALT',
               existing_server_default=sa.text("'WARN'::character varying"))
    op.alter_column('sop_steps', 'is_critical',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为关键步骤',
               existing_nullable=True)
    op.alter_column('sop_steps', 'validation_rules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='验证规则（JSON）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'action_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='操作参数（JSON）',
               existing_nullable=True)
    op.alter_column('sop_steps', 'expected_action',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='期望操作',
               existing_nullable=False)
    op.alter_column('sop_steps', 'target_part',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='目标部件ID',
               existing_nullable=True)
    op.alter_column('sop_steps', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='步骤描述',
               existing_nullable=False)
    op.alter_column('sop_steps', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='步骤标题',
               existing_nullable=False)
    op.alter_column('sop_steps', 'step_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='步骤索引（从1开始）',
               existing_nullable=False)
    op.alter_column('sop_audit_logs', 'ingest_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='记录入库时间',
               existing_nullable=False)
    op.alter_column('sop_audit_logs', 'event_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='事件发生时间',
               existing_nullable=False)
    op.alter_column('snapshots', 'adapter_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Adapter类型',
               existing_nullable=True)
    op.alter_column('snapshots', 'active_faults',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='活动故障列表',
               existing_nullable=True)
    op.alter_column('snapshots', 'sensor_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='传感器数据',
               existing_nullable=False)
    op.alter_column('snapshots', 'joint_states',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='关节状态列表',
               existing_nullable=False)
    op.alter_column('snapshots', 'trigger',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='触发原因：step_execution/manual/error',
               existing_nullable=False)
    op.alter_column('snapshots', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='快照时间',
               existing_nullable=False)
    op.alter_column('snapshots', 'step_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='步骤索引',
               existing_nullable=False)
    op.drop_constraint(None, 'session_step_records', type_='foreignkey')
    op.create_foreign_key(op.f('session_step_records_session_id_fkey'), 'session_step_records', 'training_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_session_step_records_id'), table_name='session_step_records')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_unique_constraint(op.f('schools_name_key'), 'schools', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('ux_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_robot_models_id'), table_name='robot_models')
    op.alter_column('robot_models', 'thumbnail_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='缩略图相对路径',
               existing_nullable=True)
    op.alter_column('robot_models', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='机器人描述',
               existing_nullable=True)
    op.alter_column('robot_models', 'status',
               existing_type=postgresql.ENUM('draft', 'analyzing', 'ready', name='robotstatus'),
               comment=None,
               existing_comment='状态: draft/analyzing/ready',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::robotstatus"))
    op.alter_column('robot_models', 'visibility',
               existing_type=postgresql.ENUM('private', 'shared', name='robotvisibility'),
               comment=None,
               existing_comment='可见性: private/shared',
               existing_nullable=False,
               existing_server_default=sa.text("'private'::robotvisibility"))
    op.alter_column('robot_models', 'owner_teacher_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建者教师 ID（null 表示系统内置）',
               existing_nullable=True)
    op.alter_column('robot_models', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='版本号',
               existing_nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('robot_models', 'model_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='型号名称',
               existing_nullable=False)
    op.alter_column('robot_models', 'brand',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='品牌',
               existing_nullable=False)
    op.drop_index(op.f('ix_robot_assets_id'), table_name='robot_assets')
    op.alter_column('robot_assets', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='元数据（顶点数、节点数等）',
               existing_nullable=True)
    op.alter_column('robot_assets', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='文件大小（字节）',
               existing_nullable=True)
    op.alter_column('robot_assets', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='相对存储路径',
               existing_nullable=False)
    op.alter_column('robot_assets', 'asset_type',
               existing_type=postgresql.ENUM('model_glb', 'manifest', 'thumbnail', 'upload_original', name='assettype'),
               comment=None,
               existing_comment='资产类型',
               existing_nullable=False)
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=False)
    op.drop_index(op.f('ix_multimodal_timelines_trace_id'), table_name='multimodal_timelines')
    op.drop_index(op.f('ix_multimodal_timelines_scope_type'), table_name='multimodal_timelines')
    op.drop_index(op.f('ix_multimodal_timelines_scope_id'), table_name='multimodal_timelines')
    op.drop_index(op.f('ix_multimodal_timelines_id'), table_name='multimodal_timelines')
    op.drop_index(op.f('ix_multimodal_timelines_created_by_user_id'), table_name='multimodal_timelines')
    op.drop_index(op.f('ix_multimodal_timelines_created_at'), table_name='multimodal_timelines')
    op.add_column('knowledge_documents', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.alter_column('knowledge_documents', 'generation_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='生成状态: manual/ai_draft/published',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('knowledge_documents', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联机器人型号 ID',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'uploaded_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='上传用户 ID',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'risk_level',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='风险等级',
               existing_nullable=True,
               existing_server_default=sa.text("'R0'::character varying"))
    op.alter_column('knowledge_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='PENDING/APPROVED/EXPIRED',
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('knowledge_documents', 'sop_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='关联SOP标签',
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('knowledge_documents', 'fault_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='关联故障标签 ["E001_OVERHEAT"]',
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('knowledge_documents', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='manual/guide/spec',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('knowledge_documents', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='文档全文',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='文档标题',
               existing_nullable=False)
    op.drop_constraint(None, 'fault_sop_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('fault_sop_mappings_sop_id_fkey'), 'fault_sop_mappings', 'sops', ['sop_id'], ['id'])
    op.drop_index(op.f('ix_fault_sop_mappings_id'), table_name='fault_sop_mappings')
    op.alter_column('fault_sop_mappings', 'robot_model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联机器人型号 ID',
               existing_nullable=True)
    op.alter_column('fault_sop_mappings', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='优先级（同 fault_type 多 SOP 时）',
               existing_server_default=sa.text('1'))
    op.alter_column('fault_sop_mappings', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='难度: beginner/intermediate/advanced',
               existing_nullable=False,
               existing_server_default=sa.text("'beginner'::character varying"))
    op.alter_column('fault_sop_mappings', 'sop_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联 SOP ID',
               existing_nullable=False)
    op.alter_column('fault_sop_mappings', 'fault_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='故障类型编码',
               existing_nullable=False)
    op.alter_column('fault_cases', 'solution_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='解决步骤',
               existing_nullable=True)
    op.alter_column('fault_cases', 'diagnosis_steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='诊断步骤',
               existing_nullable=True)
    op.alter_column('fault_cases', 'symptoms',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='故障症状',
               existing_nullable=True)
    op.alter_column('fault_cases', 'affected_parts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='受影响部件列表',
               existing_nullable=True)
    op.alter_column('fault_cases', 'severity',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='严重程度',
               existing_nullable=True)
    op.alter_column('fault_cases', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='故障分类',
               existing_nullable=True)
    op.alter_column('fault_cases', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='故障描述',
               existing_nullable=False)
    op.alter_column('fault_cases', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='故障名称',
               existing_nullable=False)
    op.alter_column('fault_cases', 'fault_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='故障代码',
               existing_nullable=False)
    op.drop_index(op.f('ix_evidence_cards_id'), table_name='evidence_cards')
    op.drop_index(op.f('ix_evidence_cards_created_at'), table_name='evidence_cards')
    op.drop_index(op.f('ix_evidence_cards_attempt_id'), table_name='evidence_cards')
    op.alter_column('events', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误消息',
               existing_nullable=True)
    op.alter_column('events', 'is_error',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为错误',
               existing_nullable=False)
    op.alter_column('events', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='执行耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('events', 'result',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='执行结果',
               existing_nullable=True)
    op.alter_column('events', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='操作参数',
               existing_nullable=True)
    op.alter_column('events', 'target',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='操作目标',
               existing_nullable=True)
    op.alter_column('events', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='执行的操作',
               existing_nullable=True)
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='事件时间',
               existing_nullable=False)
    op.alter_column('events', 'step_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='步骤索引',
               existing_nullable=True)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='事件类型',
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_turns_task_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_session_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_created_at'), table_name='conversation_turns')
    op.alter_column('conversation_turns', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('conversation_turns', 'metadata',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='元数据 JSON',
               existing_nullable=True)
    op.alter_column('conversation_turns', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对话内容',
               existing_nullable=False)
    op.alter_column('conversation_turns', 'role',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='角色: user/assistant/system',
               existing_nullable=False)
    op.alter_column('conversation_turns', 'step_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='步骤索引',
               existing_nullable=True)
    op.alter_column('conversation_turns', 'task_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='任务ID',
               existing_nullable=True)
    op.alter_column('conversation_turns', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_commands_idempotency_key'), table_name='commands')
    op.create_index(op.f('ix_commands_idempotency_key'), 'commands', ['idempotency_key'], unique=False)
    op.add_column('belief_state_records', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('belief_state_records', 'belief_metadata')
    op.alter_column('audit_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_analysis_tasks_id'), table_name='analysis_tasks')
    op.alter_column('analysis_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('analysis_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='失败原因',
               existing_nullable=True)
    op.alter_column('analysis_tasks', 'output_summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='分析结果摘要',
               existing_nullable=True)
    op.alter_column('analysis_tasks', 'input_document_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='输入文档 ID 列表',
               existing_nullable=True)
    op.alter_column('analysis_tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'failed', name='analysistaskstatus'),
               comment=None,
               existing_comment='任务状态',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::analysistaskstatus"))
    op.alter_column('analysis_tasks', 'task_type',
               existing_type=postgresql.ENUM('pdf_extract', 'cad_parse', 'sop_generate', 'full', name='analysistasktype'),
               comment=None,
               existing_comment='任务类型',
               existing_nullable=False)
    op.drop_index(op.f('ix_alignment_map_timeline_id'), table_name='alignment_map')
    op.drop_index(op.f('ix_alignment_map_segment_id'), table_name='alignment_map')
    op.drop_index(op.f('ix_alignment_map_ref_id'), table_name='alignment_map')
    op.drop_index(op.f('ix_alignment_map_id'), table_name='alignment_map')
    op.drop_index(op.f('ix_alignment_map_created_at'), table_name='alignment_map')
    op.drop_index(op.f('ix_alignment_map_anchor_key'), table_name='alignment_map')
    op.add_column('ai_knowledge_chunks', sa.Column('embedding_vec', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ai_knowledge_chunks_source_type'), table_name='ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_chunks_source_id'), table_name='ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_chunks_owner_user_id'), table_name='ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_chunks_course_id'), table_name='ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_chunks_attempt_id'), table_name='ai_knowledge_chunks')
    op.create_index(op.f('ix_ai_knowledge_chunks_embedding_vec'), 'ai_knowledge_chunks', ['embedding_vec'], unique=False, postgresql_ops={'embedding_vec': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
