"""Add SOP audit logs table

Revision ID: e94830cd91cf
Revises: 002
Create Date: 2026-01-19 07:09:51.148046+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94830cd91cf'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sop_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联任务 ID'),
    sa.Column('sop_id', sa.Integer(), nullable=True, comment='关联 SOP ID（可能已删除）'),
    sa.Column('trace_id', sa.String(length=64), nullable=False, comment='请求追踪 ID'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='操作者类型'),
    sa.Column('actor_id', sa.String(length=100), nullable=True, comment='操作者 ID（用户 ID 或系统名）'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='审计动作'),
    sa.Column('step_index', sa.Integer(), nullable=True, comment='步骤索引（如适用）'),
    sa.Column('result', sa.String(length=50), nullable=True, comment='执行结果'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('message', sa.Text(), nullable=True, comment='人类可读消息'),
    sa.Column('details', sa.JSON(), nullable=True, comment='结构化详情'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（如有）'),
    sa.Column('event_time', sa.DateTime(), nullable=False, comment='事件发生时间'),
    sa.Column('ingest_time', sa.DateTime(), nullable=False, comment='记录入库时间'),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_audit_logs_action'), 'sop_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_sop_audit_logs_event_time'), 'sop_audit_logs', ['event_time'], unique=False)
    op.create_index(op.f('ix_sop_audit_logs_id'), 'sop_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sop_audit_logs_sop_id'), 'sop_audit_logs', ['sop_id'], unique=False)
    op.create_index(op.f('ix_sop_audit_logs_task_id'), 'sop_audit_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_sop_audit_logs_trace_id'), 'sop_audit_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.add_column('snapshots', sa.Column('is_anomaly', sa.Boolean(), nullable=False, comment='是否包含异常'))
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_snapshots_task_id'), 'snapshots', ['task_id'], unique=False)
    op.create_index(op.f('ix_sop_steps_id'), 'sop_steps', ['id'], unique=False)
    op.create_index(op.f('ix_sop_steps_sop_id'), 'sop_steps', ['sop_id'], unique=False)
    op.create_index(op.f('ix_sops_applicable_model'), 'sops', ['applicable_model'], unique=False)
    op.create_index(op.f('ix_tasks_sop_id'), 'tasks', ['sop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_sop_id'), table_name='tasks')
    op.drop_index(op.f('ix_sops_applicable_model'), table_name='sops')
    op.drop_index(op.f('ix_sop_steps_sop_id'), table_name='sop_steps')
    op.drop_index(op.f('ix_sop_steps_id'), table_name='sop_steps')
    op.drop_index(op.f('ix_snapshots_task_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_column('snapshots', 'is_anomaly')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_sop_audit_logs_trace_id'), table_name='sop_audit_logs')
    op.drop_index(op.f('ix_sop_audit_logs_task_id'), table_name='sop_audit_logs')
    op.drop_index(op.f('ix_sop_audit_logs_sop_id'), table_name='sop_audit_logs')
    op.drop_index(op.f('ix_sop_audit_logs_id'), table_name='sop_audit_logs')
    op.drop_index(op.f('ix_sop_audit_logs_event_time'), table_name='sop_audit_logs')
    op.drop_index(op.f('ix_sop_audit_logs_action'), table_name='sop_audit_logs')
    op.drop_table('sop_audit_logs')
    # ### end Alembic commands ###
